### ISSUE TITLE
Error while defining FALKEN_FEELERS attribute in Observations

### ISSUE THREAD

**Issue by sandip1604** [google-research/falken#11]
I am trying to implement the Falken Observation space using a structure like the README.md Documentation of the C++ SDK. 

Here is the code of my structure:

    struct Robot : public falken::EntityBase{
          Robot(falken::EntityContainer& container, const char* name)
            : falken::EntityBase(container, name){}
        }; 

    struct MyObservations : public falken::ObservationsBase {
      MyObservations()
        : FALKEN_FEELERS(laser, 50, 50.0f, 3.22f, 0),
          FALKEN_ENTITY(my_robot) {}

      falken::FeelersAttribute laser;
      Robot my_robot;
    };
 
I get the following Error while Building the Code

![image](https://user-images.githubusercontent.com/60662785/126388118-f82b1e8a-2821-4a57-82fa-c22c66554d77.png)

I might have made a silly mistake!

**Comment by hmoraldo** [comment]
I think the issue may be in some of the surrounding code.

In any case, you may want to familiarize yourself with sdk/cpp/src/core/service_test.cc first (since it uses FALKEN_FEELERS), and maybe try any observations that don't work in your own code there first, as means of debugging the issue.
