### ISSUE TITLE
Falken coordinate system assumptions

### ISSUE THREAD

**Issue by haowang1013** [google-research/falken#12]
Hi,

I'm trying to get falken to work in Unreal Engine but I'm having a hard time to get the desired results.
I suspect this may have to do with UE4 uses a Z up left hand coordinate system, as opposed to the Y up one assumed by falken.
I also noticed that the hello falken project has some special treatment for the 2D angle when converting it to quaternion, quote:
```
// Falken uses 3D coordinates. We therefore interpret game 2D locations as
// 3D positions on the XZ plane. We translate a HelloFalken angle into a
// quaternion that specifies a rotation around the Y-axis. We need to
// modify the angle in two ways before constructing the quaternion:
// 1) We need to offset the angle by 90 degrees. This is because Falken
//    assumes that an object at neutral orientation points towards the
//    Z-axis, but an object at neutral orientation in HelloFalken points
//    towards the X-axis.
// 2) Falken uses a left-handed coordinate system, so rotations around the
//    Y-axis are clockwise (when looking at the XZ plane from above). Since
//    angles in HelloFalken are counter-clockwise, we need to negate the
//    angle.
```
I'm mostly curious why falken has such a limitation/assumption of the "default" coordinate system used.
Which part of the code base relies on such assumption to work?

Thanks!

**Comment by haowang1013** [comment]
FYI, I managed to figure out a UE4 to Falken conversion logic which seems to be working in my test case:

```
falken::Position FFalkenUtils::ToFalken(const FVector& Position)
{
	return { Position.Y, Position.Z, Position.X };
}

falken::Rotation FFalkenUtils::ToFalken(const FRotator& Rotator)
{
	const auto Rotation = falken::Rotation::FromEulerAngles(Rotator.Pitch * DEG2RAD, Rotator.Yaw * DEG2RAD, Rotator.Roll * DEG2RAD);
	return Rotation;
}
```

**Comment by hmoraldo** [comment]
The code that handles the joystick interaction with the camera uses this assumption.

Closing since the main issue is solved.
