### ISSUE TITLE
Unable to use the Function falken::Rotation.FromEulerAngles(float roll, float pitch, float yaw)

### ISSUE THREAD

**Issue by sandip1604** [google-research/falken#15]
Hello Auther, 
I am trying to use the tool to learn robot navigation where I have written a game wrapper to interact with the falken in C++. 

I am trying to use the` fallen::Roation `class to set the rotation and then use this instance to set the entity rotation as follows.

```
falken::Rotation entity_rotation; 
entity_roation.FromEulerAngles(roll, pitch,yaw);
brain_spec.observations.rotation.set_rotation(entity_rotation);
```
Upon building my game wrapper CMake gives me the following error. 

![error](https://user-images.githubusercontent.com/60662785/127592408-6f25621e-207d-4372-84aa-51a1b369d578.png)

I ran the following sanity checks to make sure that I am linking the Falken right. 

1. Including the Falken directory that has Findfalken.cmake into the `CMAKE_MODULE_PATH`

    `list(APPEND CMAKE_MODULE_PATH /home/sandip.patel/teleop_game/src/game_engine/falken_cpp_sdk)
`
2. Find Falken with find package in the CMakeList
     `find_package(falken REQUIRED)`

3. Linking the Falken with executable:
    ` target_link_libraries(listener_mutex falken_cpp_sdk)`

I even checked if the Falken is linked correctly by checking if Falken shared object library is linked or not. 

`libfalken_cpp_sdk.so =>/home/sandip.patel/teleop_game/src/game_engine/falken_cpp_sdk/lib/Linux/Release/libfalken_cpp_sdk.so (0x00007f6156323000)`

So, everything seems fine to me. Am I missing anything that leads to this error of undefined reference in the above image?

Thanks!

**Comment by hmoraldo** [comment]
Do tests pass? If environments/cpp/hello_falken works, an easy way to debug would be to start by making modifications to its CMakeFiles.txt first.

Also depending on the compiler you are using, it may be easier to build the library and linking to it, instead of using the prebuilts.

**Comment by sandip1604** [comment]
Hello, Falken works for me!. Will try to build from the source. But I am curious in theory shouldn't the fallen try to learn the game even if we skip the rotation part for now? I mean the rotation for the entity is not the required attribute right?

**Comment by hmoraldo** [comment]
If you are using the joystick & camera logic the rotation is relevant (I may be missing some implementation detail though). Even if it wasn't, the fact that it's missing that symbol will likely mean it would be unable to find other symbols as well if you stopped using rotations.
