### ISSUE TITLE
unique vs shared ptr

### ISSUE THREAD

**Issue by mattlegro** [google-research/falken#17]
Hello.

Following along with the README for integrating the Falken C++ SDK, I get errors related to the pointer type. In the readme, it suggests that I use `unique_ptr` in the lines

```
std::unique_ptr<falken::Session> session =
    brain->StartSession(falken::Session::kTypeInteractiveTraining, kMaxSteps);

std::unique_ptr<falken::Episode> episode = session->StartEpisode();
```
but I get an error under `brain->`: C++ no suitable user-defined conversion from "std::shared_ptr<falken::Session>" to "std::unique_ptr<falken::Session>, std::default_delete<falken::Session>>" exists. Similar error with regards to `session->`. If I change those lines to use `shared_ptr` instead of unique, it goes away. Is this an okay solution?

**Comment by hmoraldo** [comment]
Yes, both test_app and hello_falken use shared_ptr; you can use environments/cpp/hello_falken or test_app for reference about this.
