### ISSUE TITLE
Coordinate System Confusion

### ISSUE THREAD

**Issue by mattlegro** [google-research/falken#22]
Hey,

So I'm having problems getting my brains to learn, and I am trying to double check if I am feeding falken position and location information properly. Based on this [thread](https://github.com/google-research/falken/issues/12) and the quoted comment from math_utils.h in hellofalken:
```
  // Falken uses 3D coordinates. We therefore interpret game 2D locations as
  // 3D positions on the XZ plane. We translate a HelloFalken angle into a
  // quaternion that specifies a rotation around the Y-axis. We need to
  // modify the angle in two ways before constructing the quaternion:
  // 1) We need to offset the angle by 90 degrees. This is because Falken
  //    assumes that an object at neutral orientation points towards the
  //    Z-axis, but an object at neutral orientation in HelloFalken points
  //    towards the X-axis.
  // 2) Falken uses a left-handed coordinate system, so rotations around the
  //    Y-axis are clockwise (when looking at the XZ plane from above). Since
  //    angles in HelloFalken are counter-clockwise, we need to negate the
  //    angle.
```
the falken service expects a left-handed axis with +y pointing out of the page, making +z downward while +x is to the left. My program uses a left-handed coordinate system with +z pointing out of the page, +y pointing up and +x pointing left. So to convert positions between the two seems simple, where I need to make an (x,y,z) in my program (x,z,-y) when I feed it to falken. The rotation thing is a bit more involved however, but I have the pitch, yaw, and roll for my player as defined relative to my axes, and since it is a left handed axis system where positive rotations around the out of the page axis increases in the clockwise direction, as expected by falken, I think converting these to a quaternion to feed to falken should work.

The use case is pretty simple, right now I am just trying to train an agent to steer toward a target, basically a reimplementation of HelloFalken in my program, but it keeps crashing on passing control to the brain because the brain isn't able to learn and outputs nans.

Am I missing something?

**Comment by hinasakazaki** [comment]
Hey Matt, can you try checking if the quaternion is NaN before sending observations to Falken and don't send if it is NaN and see if that works?

**Comment by Ronith-liyanage** [comment]
Can you hepl me woth my issue 
>> https://github.com/google-research/falken/issues/27#issue-1050953480
