### ISSUE TITLE
Selected model None for training session 

### ISSUE THREAD

**Issue by nubfight4** [google-research/falken#26]
I was trying to do run the HelloFalken demo on Unity and after playing 10-20 games letting falken run, the player isn't really moving unless I move it myself. 

I tried checking the dashboard and it did record the episodes where I reached the goal when I was on the recording part of the demo.

The one thing I found out was that on the falken service cmd it gave this line on each episode

` I1110 17:25:04.257828 34272 model_selector.py:94] Selected model None for training session projects/falken_test/brains/fb5b7334-d6fb-48d9-8ab2-7d8ae98526cc/sessions/0e13a019-4713-4852-baa6-465d2003e806.`

I was trying to figure out how to select a model but am still lost

**Comment by hinasakazaki** [comment]
Looks like models are not getting trained. Do you see any logs from the falken learner side like "Waiting for assignment"? They should show up when you run the falken service. https://github.com/google-research/falken/blob/main/service/README.md#launch-the-service

**Comment by nubfight4** [comment]
> Looks like models are not getting trained. Do you see any logs from the falken learner side like "Waiting for assignment"? They should show up when you run the falken service. https://github.com/google-research/falken/blob/main/service/README.md#launch-the-service

I saw a "Waiting for assignment" log when I started the falken service, and when I clicked Play on the Unity Editor demo, it shows the  "Selected model None for training session" log that I mentioned in the post every time I finished a successful episode.

**Comment by hinasakazaki** [comment]
Nice. The reason why I asked about  "Waiting for assignment" log is because that one is from the [learner portion](https://github.com/google-research/falken/blob/main/service/learner/learner.py) of the service, where as "Selected model None for training session" log is from the [API portion](https://github.com/google-research/falken/blob/main/service/api/model_selector.py) of the service. 

I would recommend looking at other logs in the learner portion, such as if training is happening, by adding logs in the learner code yourself or looking at existing logs. For example, do you see logs like "Finished adding X new chunks with Y demo frames" logged [here](https://github.com/google-research/falken/blob/main/service/learner/assignment_processor.py#L356)? Or "Trained X steps in total..." logged [here](https://github.com/google-research/falken/blob/main/service/learner/brains/continuous_imitation_brain.py#L615)?

**Comment by nubfight4** [comment]
I don't see the logs you mentioned, should I assume the training wasn't happening/recording? 
I also found this log if it helps "Failed to get offline model and model from starting snapshot for session X. Returning empty model."

**Comment by hinasakazaki** [comment]
Sounds like the learner is not picking up the assignments from the API, or the API is not receiving the assignments.
The `I tried checking the dashboard and it did record the episodes where I reached the goal when I was on the recording part of the demo.` bit makes me think that learner picking up assignments is where it is broken.

Can you try debugging (by adding log statements or using the log statements existing) to see how far the data from your gameplay is making it through the learner? 

I would start with [storage.py receive_assignment](https://github.com/google-research/falken/blob/eecd8ab255e5bf3ea31c209bd1ce2f25e7965814/service/learner/storage.py#L384) and add a few logs there like in line 412, `falken_logging.error('QUEUE EMPTY')`, in line 417, `falken_logging.error('READING ITEM')` and in the line after the read call `falken_logging.error('SUCCESSFUL READ')` or something like that. 

If the queue seems always empty, it's likely that the storage layer for learner is broken, in which case, I'd check the directory it's reading from by adding logs at the [resource_store.py](https://github.com/google-research/falken/blob/eecd8ab255e5bf3ea31c209bd1ce2f25e7965814/service/data_store/resource_store.py). See where it's writing to by logging the [self._get_path(res_id, timestamp_micros)](https://github.com/google-research/falken/blob/eecd8ab255e5bf3ea31c209bd1ce2f25e7965814/service/data_store/resource_store.py#L169) and see where it's reading from by logging the [same thing](https://github.com/google-research/falken/blob/eecd8ab255e5bf3ea31c209bd1ce2f25e7965814/service/data_store/resource_store.py#L200) at `read`.

**Comment by nubfight4** [comment]
I wasn't sure how to log **self._get_path(res_id, timestamp_micros)** because importing falken_logging was blocking me from turning on the falken service.

The logs are attached in this .zip file after adding what you have suggested to try debugging in **storage.py**

[service.zip](https://github.com/google-research/falken/files/7535980/service.zip)


I also noticed that queue was only empty if I ran the service without turning on the game and just let the falken service run. I don't get the "Queue Empty" log after having some gameplay

```
I1115 12:48:17.271706  1576 storage.py:450] Recording assignment done.
I1115 12:48:17.273701  1576 storage.py:456] Recorded assignment done.
I1115 12:48:17.273701  1576 learner.py:106] Waiting for assignment.
E1115 12:50:17.274491  1576 storage.py:413] QUEUE EMPTY
E1115 12:50:17.274491  1576 storage.py:426] SUCCESSFUL READ
I1115 12:50:17.279474  1576 learner.py:106] Waiting for assignment.
E1115 12:52:17.284329  1576 storage.py:413] QUEUE EMPTY
E1115 12:52:17.284329  1576 storage.py:426] SUCCESSFUL READ
I1115 12:52:17.286320  1576 learner.py:106] Waiting for assignment.
```

These were the logs if it helps.

**Comment by hinasakazaki** [comment]
That's good, sounds like that the learner is able to read assignments from your gameplay. 

In your logs, I see proper logs of processing assignment, creating an agent, and training from them. The issue seems to happen in exporting the model:
```
E1115 13:02:04.884747 13808 learner.py:281] Exception found when processing assignment: EndVector() takes 1 positional argument but 2 were given.
...
  File "C:\Users\[Redacted]\GitHub\falken\service\learner\brains\saved_model_to_tflite_model.py", line 101, in _patch_tflite_model
    builder.Finish(lite_model.Pack(builder),
  File "C:\Users\[Redacted]GitHub\falken\service\generated_flatbuffers\tflite\Model.py", line 322, in Pack
    operatorCodes = builder.EndVector(len(self.operatorCodes))
```

This seems to be an issue with TF: https://github.com/tensorflow/tensorflow/issues/51590 Can you try updating TF? I think just rerunning `pip install --upgrade tensorflow` should work. If issue persists, can you show us what you get with `pip show tensorflow`?

**Comment by nubfight4** [comment]
I updated it and it still persisted. This is what I got from `pip show tensorflow`.
```
Name: tensorflow
Version: 2.7.0
Summary: TensorFlow is an open source machine learning framework for everyone.
Home-page: https://www.tensorflow.org/
Author: Google Inc.
Author-email: packages@tensorflow.org
License: Apache 2.0
```

**Comment by hinasakazaki** [comment]
Try `pip install tensorflow==2.6.0` ?

**Comment by nubfight4** [comment]
Actually it works now! I just forgot to change the falken_config after accidentally creating a new one just now. Thanks for the help!

**Comment by hinasakazaki** [comment]
Great! Glad to help :)
