### ISSUE TITLE
Stuck at installation 

### ISSUE THREAD

**Issue by Ronith-liyanage** [google-research/falken#27]
Hi ,
Can anyone help me with the setup installation in falken unity  sdk in windows 
I am done with the prerequests
>>Python is installed (version is the latest)
>>Pip pakage installer is installed 
>>openssl is installed  (all system variables are set )

And i downloaded the falken unity sdk from the relase page and extracted to my drive 

Issue 
When following the instructions at [Launcher - intructions ](https://github.com/google-research/falken/blob/main/service/README.md#launch-the-service) 

I am unclear about the steps ...
when running : Run the following command at the root of the falken repo:
python service/launcher.py --project_ids falken_test

My system says that there is no directory or file called laucher.py 

Can someone help me with the rest of the installation as I am hoping to use falken with unity 

Thanks

**Comment by Ronith-liyanage** [comment]
If someone provide with an deeper explanation on the installation procedure will help me a lot ...
thanks

**Comment by hinasakazaki** [comment]
When you cloned the falken repo, there should be a directory called service which corresponds to this path in the repo: https://github.com/google-research/falken/tree/main/service. launcher.py refers to the file here: https://github.com/google-research/falken/blob/main/service/launcher.py. You just need to `cd` in your local file system where the repo is cloned, and run `python service/launcher.py --project_ids falken_test`. 

For example, you may have cloned the repository in your Downloads folder. In which case, maybe you'd do:
```
cd Downloads
cd falken-main
python service/launcher.py --project_ids falken_test
```

You don't mention in your initial post that you cloned the [repository](https://github.com/google-research/falken). Please make sure you do that first.

**Comment by Ronith-liyanage** [comment]
Thanks
It worked 
After coloning and downloading the zip of the full file an extracted it and followed the instructions
