### ISSUE TITLE
_lockfile.py:385 timed out

### ISSUE THREAD

**Issue by jurys22** [google-research/falken#28]
Sometimes I get this error when re-open Falken after it was closed on my powershell console by pressing ctrl-c or just closing the window. 

Is there a good way to shut it down or a reason behind this error? 

![image](https://user-images.githubusercontent.com/93677581/141534492-a64eeffa-af72-401c-95ec-6d8eca38c8d0.png)

**Comment by hmoraldo** [comment]
This should be ok IIRC, it just means that the elements of the queue have timed out because they are not being trained anymore.

**Comment by hmoraldo** [comment]
You could get rid of the message by modifying the dependency that handles the lock files; or by removing those files manually yourself instead of letting it detect the time outs. But by itself it should be harmless.
